import org.jetbrains.kotlin.gradle.dsl.KotlinJsCompile
import org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin.Companion.kotlinNodeJsRootExtension

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

plugins {
    kotlin("multiplatform") version "2.1.20"
}

repositories {
    mavenLocal()
    mavenCentral()
}

kotlin {
    js(IR) {
        useEsModules()
        nodejs {}
        binaries.executable()
        generateTypeScriptDefinitions()
    }

    sourceSets {
        commonMain {
            dependencies {
            }
        }
    }
}